server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10GB #最大文件大小
      max-request-size: 10GB
  application:
    name: DynamicWordExport #项目名称
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.8.69:3306/yfkb?rewriteBatchedStatements=true
    username: root
    password: bonc.123

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: mybatis.plus.code.generate.demo
  global-config:
    db-config:
      id-type: auto
      insert-strategy: ignored